#!/bin/bash

player_status=$(playerctl --player=spotify status 2> /dev/null)
if [[ $? -eq 0 ]]; then
    metadata="$(playerctl --player=spotify metadata artist 2> /dev/null) - $(playerctl --player=spotify metadata title 2> /dev/null)"
fi

# Foreground color formatting tags are optional
if [[ $player_status = "Playing" ]]; then
    echo "$metadata"      # Orange when playing
elif [[ $player_status = "Paused" ]]; then
    echo "Paused"      # Greyed out info when paused
else
    echo "No player" # Greyed out icon when stopped
fi

case $BLOCK_BUTTON in
  1) playerctl --player=spotify play-pause ;;
  2) playerctl --player=spotify play-pause ;;
  3) playerctl --player=spotify play-pause ;;
  4) playerctl --player=spotify previous ;; # scroll up, increase
  5) playerctl --player=spotify next ;; # scroll down, decrease
esac

