#! /bin/sh
killall -q sxhkd
sxhkd &

~/.config/polybar/launch.sh
compton -b
xrdb ~/.Xresources

bspc monitor DisplayPort-0 -d 1:1 2:2 3:3 4:4 5:5
bspc monitor DVI-D-0 -d 6:6 7:7 8:8 9:9 10:10

bspc config border_width 2
bspc config window_gap 2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
