#!/bin/bash


PLAYER_NAME="spotify"
player_status=$(playerctl --player="$PLAYER_NAME" status 2> /dev/null)
if [[ $? -eq 0 ]]; then
    metadata="$(playerctl --player="$PLAYER_NAME" metadata title 2> /dev/null) by $(playerctl --player="$PLAYER_NAME" metadata artist 2> /dev/null)"
fi

# Foreground color formatting tags are optional
if [[ $player_status = "Playing" ]]; then
    echo "$metadata"      # Orange when playing
elif [[ $player_status = "Paused" ]]; then
    echo "Paused"      # Greyed out info when paused
else
    echo "No player" # Greyed out icon when stopped
fi
