#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    if [ "$m" = "DP-1" ]; then
        MONITOR=$m TRAY_POS="right" polybar --reload mybar &
    else
        MONITOR=$m polybar --reload mybar &
    fi
  done
else
  polybar --reload mybar &
fi
